//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umgProyecto3._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gest_cheque
    {
        public int serie { get; set; }
        public Nullable<System.DateTime> ingreso { get; set; }
        public string cuenta { get; set; }
        public string estado { get; set; }
        public string moneda { get; set; }
    
        public virtual asign_cheque_cp asign_cheque_cp { get; set; }
        public virtual gest_cuenta gest_cuenta { get; set; }
    }
}
