//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umgProyecto3._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gest_factura
    {
        public int serie { get; set; }
        public string estado { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual mov_factura_credito mov_factura_credito { get; set; }
    }
}
