//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umgProyecto3._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_debito_cc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nota_debito_cc()
        {
            this.saldos = new HashSet<saldos>();
        }
    
        public int correlativo { get; set; }
        public System.DateTime fecha { get; set; }
        public string descripcion { get; set; }
        public int serie_factura { get; set; }
        public Nullable<int> idempresa { get; set; }
        public string pago { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual gest_cliente gest_cliente { get; set; }
        public virtual mov_factura_credito mov_factura_credito { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saldos> saldos { get; set; }
    }
}
