//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umgProyecto3._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nota_debito_cp
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public nota_debito_cp()
        {
            this.saldos = new HashSet<saldos>();
        }
    
        public int correlativo { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> nfactura { get; set; }
        public Nullable<int> idempresa { get; set; }
        public Nullable<decimal> abono { get; set; }
        public Nullable<int> serie_cheque { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual asign_cheque_cp asign_cheque_cp { get; set; }
        public virtual gest_proveedor gest_proveedor { get; set; }
        public virtual mov_factura_pagos mov_factura_pagos { get; set; }
        public virtual usuario usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saldos> saldos { get; set; }
    }
}
