//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace umgProyecto3._2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class saldos
    {
        public int correlativo { get; set; }
        public Nullable<int> c_pago { get; set; }
        public Nullable<int> c_venta { get; set; }
        public Nullable<int> c_deposito { get; set; }
        public Nullable<int> c_transferencia { get; set; }
    
        public virtual desposito desposito { get; set; }
        public virtual mov_trasf_cuenta mov_trasf_cuenta { get; set; }
        public virtual nota_debito_cc nota_debito_cc { get; set; }
        public virtual nota_debito_cp nota_debito_cp { get; set; }
    }
}
